Title:
  MainTitle: '&1[&bSkillTree&1]&r'
  ItemGUI: '&1[&9 %class% &1]&r'
GUI:
  InvaildSkills: Skill %skill% has no valid identifiers and can not be used on the menu! Please contact the author to fix the skill.
  Lore: '&eClick for use!'
  LoreLevel: '&f&oSkillLevel: %level%/%maxLevel%'
  LoreMana: '&f&oMana: %manaCost%'
  TitleSkill: '&2&l[&r&a%skill%&2&l]'
  TitleChoose: '&1== &bChoose your class! &1=='
Hologram:
  MessageEXPCurrent: '&a&l+ &2&o%gained%XP'
  MessageEXPMax: '&2[ &9%current%&1/&9%needed% &2]'
Info:
  SkillPoints: '&b[&rYou currently have &9%points% &rSkillPoints&b]'
Warning:
  TooHighLevel: '%player%''s skills are at a too high level!'
Error:
  AdminNotEnoughArguments: '&cNot enough arguments: /skilladmin <command> (amount)
    [sender]'
  PermissionDenied: '&cYou don''t have enough permissions'
  CommandUsage: '&cCorrect usage: /skilladmin (set/give/remove/clear/reset) <nick>'
  PlayerOffline: '&cSorry, player %player% is offline.'
Admin:
  PlayerResetSuccess: '&2You have reseted %player%''s skills'
  SelfResetSuccess: '&2You have reseted your character'
  SkillPointsAddSuccess: You have added %player% %skillpoints% skillpoint(s).
  SkillPointsRemoveSuccess: You have removed %skillpoints% skillpoint(s) from %player%.
Help:
  '1': '&9&l=._______==&1[&b&oSkillTree&1]&9&l==_______.='
  '2': '&b/&9ST Up &b<&oskill&b&b> [&oamount&b] &r- level up a skill'
  '3': '&b/&9ST Down &b<&oskill&b> [&oamount&b] &r- de-levels a skill'
  '4': '&b/&9ST List &r- list of all unlocked skills'
  '5': '&b/&9ST Unlocks &r- lists all adjacent unlockable skills'
  '6': '&b/&9ST Info &b<&oskill&b> &r- all info on a skill'
  '7': '&b/&9ST GUI &r- show upgrading skills GUI (DEV)'
  '8': '&b/&9ST Admin &b<&ocommand&b> (&oamount&b) [&oplayer&b]'