# Go to WHeroesAddon.jar/config.yml for info
# Configs for WHeroesAddon
SkillTree:
  #Are the SkillTree enabled [WARNING: Need tests!]?
  Enabled: true

  #Sets how many SkillPoints the player will earn/lose per level.  
  PointsPerLevel: 1

  #Sets the cost to unlock a skill (PLANNED)
  #CostToUnlock: 0

  #Sets the cost to level up a skill (PLANNED)
  #CostToLevelUp: 0

  #Sets the cost to level down a skill (PLANNED)
  #CostToLevelDown: 0

  #Sets the cost to reset all stats (PLANNED)
  #CostToReset: 0

# Configs for Holograms
Hologram:
  #Are the Holograms enabled?
  Enabled: true

  #How much holograms should be
  Time: 250

# If is class choosing on login is enabled (menu definied by SMS)?
UseJoinChoose: true

# Configs for ManaPotions [WARNING: It's NOT work]
ManaPotion:
  #Are the ManaPotions enabled?
  Enabled: false

  #Mana potion data value
  Potion-ID: 8197

  #Should players regain a flat amount of mana (false) or a random amount (true)
  RegainStatic: false

  #Flat mana regain amount (if regain-static is true)
  Regain: 50

  #Range for random mana regain amount (if regain-static is false)
  RegainMin: 1
  RegainMax: 100