#Sets how many SkillPoints the player will earn/lose per level.
points-per-level: 1

#Configs for holograms
holograms: true
hologram_time: 250

#If is class choosing on login is enabled?
useJoinChoose: true

#If is class ManaPotion is enabled?
useManaPotion: true

# Mana potion data value
potion-id: 0
# Should players regain a flat amount of mana (false) or a random amount (true)
regain-static: false
# Flat mana regain amount (if regain-static is true)
regain: 50
# Range for random mana regain amount (if regain-static is false)
regain-min: 1
regain-max: 100

#Sets the cost to unlock a skill (PLANNED)
#cost-to-unlock: 0

#Sets the cost to level up a skill (PLANNED)
#cost-to-level-up: 0

#Sets the cost to level down a skill (PLANNED)
#cost-to-level-down: 0

#Sets the cost to reset all stats (PLANNED)
#cost-to-reset: 0